name: 'jaffle_shop'

config-version: 2
version: '0.1'

profile: 'sqlserver-db'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]

log-path: '/tmp/dbt_log/'
target-path: "/tmp/dbt_target/"  # directory which will store compiled SQL files
# packages-path: "/tmp/dbt_packages/"

clean-targets:         # directories to be removed by `dbt clean`
    - "/tmp/dbt_target/"
    # - "/tmp/dbt_packages/"
    - "/tmp/dbt_log/"

require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  jaffle_shop:
      materialized: table
      staging:
        materialized: view
